### ISSUE TITLE
Add electron publish commands

### ISSUE THREAD

**Issue by MoneerShatat** [BionicFramework/BionicElectronPlugin#3]
Hi,

this is great job what you did here.
how to run the blazor electron app without using the bionic cmd line "bionic platform electron serve".
is there any possibility to publish or package the electron blazor app.
can i use electron-packager or electron-builder to do that.

thanks in advanced

**Comment by bmsantos** [comment]
@MoneerShatat, yes, you should be able to use those packages just fine. Just go into platforms/electron directory and add whatever packages you need to the package.json.

**Comment by bmsantos** [comment]
To call those commands from the project root directory you may want to make use of Bionic Blast Scripting (calling it scripting is an overstatement at this time):
https://bionicframework.github.io/Documentation/blast/

**Comment by MoneerShatat** [comment]
@bmsantos many thanks for the fast answer.
I will try it.

**Comment by MoneerShatat** [comment]
Today I tried the electron-packager successful to package Blazor app on electron platform.

Thank you again
